### ISSUE TITLE
Investigate JS Spreadsheet

### ISSUE THREAD

**Issue by amy-hoangg** [lightsheet-team/lightsheet#1]
Some 
- Should we have it in dependencies?
- Maybe research the features and have a running demo on which parts we can borrow or use?
- Whether we can use JS Spreadsheet to generate the initial view of the sheet?

**Comment by lakosd** [comment]
- [ ] Investigate is the rendering part can be "separated" from their own "backend"

**Comment by lakosd** [comment]
> Should we have it in dependencies?
No

**Comment by lakosd** [comment]
We will reuse code from [Jspreadsheet CE](https://github.com/jspreadsheet/ce) to implement our UI. We won't have it as a dependency, however.

JCE has almost all of the features (in terms of UI) that we have as requirements.
