### ISSUE TITLE
Resolve issues with initial data structure

### ISSUE THREAD

**Issue by Fluglow** [lightsheet-team/lightsheet#10]
* resolving/modifying formatting for a single cell, row or column
    * if formatting is set for a column, how is specific formatting data of cells in that column discarded?
* Column/row insertion, both data and formatting
* Cell formatting grouping? If all cells but not rows/columns have common formatting, is the format defined by cell-specific objects or one shared object?

**Comment by Yousif-FJ** [comment]
This issue will be closed when we decide on the final data structure

**Comment by Yousif-FJ** [comment]
This issue is mostly resolved as Jaakko created a python demo code which was discussed and agreed upon.
Python code is [here](https://github.com/lightsheet-team/lightsheet-python)

**Comment by Fluglow** [comment]
Core structure:
![LSv3-core](https://github.com/lightsheet-team/lightsheet/assets/38987331/30271349-65fa-447d-80f0-70695ac47589)
Event structure:
![LSv3-event](https://github.com/lightsheet-team/lightsheet/assets/38987331/584f08d1-0fa5-4fc4-b074-0bf9e797a389)
Formatting and expression handling structure:
![LSv3-evaluation](https://github.com/lightsheet-team/lightsheet/assets/38987331/c6ac3db8-0743-4166-beed-185849aa320e)
Context, event system
![LSv3-attachments](https://github.com/lightsheet-team/lightsheet/assets/38987331/86c00f09-97ad-4860-bfc9-03037b45d83f)
