### ISSUE TITLE
Figma prototypes for different scenarios

### ISSUE THREAD

**Issue by lakosd** [lightsheet-team/lightsheet#20]

**Comment by amy-hoangg** [comment]
https://www.figma.com/file/wMqJ7ze9ExRWoB1yk053s4/UI-version-2.0?type=design&node-id=5%3A2&mode=design&t=pgUs2j6cxpQAHBJ7-1

**Comment by rafinutshaw** [comment]
LGTM! but we may need to change it as we progress but that can be done on the go.

**Comment by rafinutshaw** [comment]
LGTM! but we may need to change it as we progress but that can be done on the go.
