### ISSUE TITLE
Setup GitHub Actions for linting

### ISSUE THREAD

**Issue by lakosd** [lightsheet-team/lightsheet#28]

**Comment by GimanthaDissanayake** [comment]
Raised a Pull Request.

**Comment by GimanthaDissanayake** [comment]
![image](https://github.com/lightsheet-team/lightsheet/assets/26846740/d96cb98a-3300-499f-b031-09adbaf73260)

It seems one of the Rules set up by @Yousif-FJ is blocking running the GitHub actions script.  This means we can't use actions from the GitHub marketplace directly, like actions/checkout@v2 and actions/setup-node@v2.

Can you change the Policy? This can be done in the GitHub organization settings under `Actions -> Actions permissions`.
