### ISSUE TITLE
Setup the dev-tooling and initalize repository

### ISSUE THREAD

**Issue by julkunensuvi** [lightsheet-team/lightsheet#3]

**Comment by Yousif-FJ** [comment]
After discussion and experiments, we decided the following
- We will use Vite as the build tool for the package
- A second project will reference the package (using a folder dependency) to run it 

The project will work as follows:
- Vite will build and watch the package 
- The second project will work in hot reload

The benefits compared to other approaches and tools:
- No need to re-run build or link commands
- A hot-reload like experience where changes are reflected almost instantly

**Comment by Yousif-FJ** [comment]
Single project approach was followed.
This is achieved by having the dev command run the index.html file, while the build command just package the code
