### ISSUE TITLE
Handle cells styling in core 

### ISSUE THREAD

**Issue by Yousif-FJ** [lightsheet-team/lightsheet#36]

**Comment by Fluglow** [comment]
Implement methods for manipulating sheet styling, such as [getStyleAt](https://github.com/lightsheet-team/lightsheet-python/blob/4cc0764350d79a713ba33360b315b3af549b24f8/core/structure/Sheet.py#L169C9-L169C21) and methods for setting column, row and cell `CellStyle`. Don't consider range operations for now, as they aren't implemented in the UI. The UI can communicate with the core by passing `CellStyle` objects that are applied to the data structures accordingly.
