### ISSUE TITLE
Create the mid project presentation

### ISSUE THREAD

**Issue by lakosd** [lightsheet-team/lightsheet#40]
> Each team has about 8 minutes for their presentation:
> - Introduce your project topic and customer. Explain what you actually do in the project.
> - Introduce who you are, main roles.
> - Meetings, communication with the customer, communication with the group.
> - Tools and technologies, methods and processes.
> - Other management issues.
> - Current project risks and avoidance.
> - Show what you have developed so far, give a demo.
> - Presentation language is English.
>
> After the presentation, couple of minutes are used for questions and discussion.

Depends on #41

**Comment by julkunensuvi** [comment]
Slides: https://tuni-my.sharepoint.com/:p:/g/personal/suvi_julkunen_tuni_fi/EVeinvBhoEFIh8NmqMNC1QMBStsOU69YCYOwLPnuk1bcBA?e=m2qXbm
