### ISSUE TITLE
Create project test plan

### ISSUE THREAD

**Issue by Yousif-FJ** [lightsheet-team/lightsheet#65]

**Comment by lakosd** [comment]
Here's an example test plan shared by the course teachers: https://github.com/dmitrymarokhonov/GroupX-Activation-game/wiki/Test-plan

**Comment by julkunensuvi** [comment]
Created test plan here
 
[https://tuni.sharepoint.com/:w:/r/sites/TG-Spreadsheetsoftwareproject/Jaetut%20asiakirjat/General/G24-PROJ-TestPlan.docx?d=w01235fe8d1bf45ad865ca1c14828c6e2&csf=1&web=1&e=V6ggxm](https://tuni.sharepoint.com/:w:/r/sites/TG-Spreadsheetsoftwareproject/Jaetut%20asiakirjat/General/G24-PROJ-TestPlan.docx?d=w01235fe8d1bf45ad865ca1c14828c6e2&csf=1&web=1&e=V6ggxm&isSPOFile=1)
 
Could someone do a quick check, especially considering performance testing (Can we remove this phase to save time?) Even though there are requirements that maybe should be tested, like Response time should be less than a second. 
 
Also security testing might not be that useful as the package is not integrated to the actual system in this phase, but there is the cross site scripting and SQL injection requirement. Can we somehow make this really easy or remove this phase too :D Also, any other suggestions to make the testing less time consuming as we probably want to prioritize implementation stuff?
